name: Cron Test

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show cron test info
        run: |
          echo "Cron test ran"
          echo "Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "UTC time:"
          date -u
          echo "Runner local time:"
          date
